"""
EVIDENCE-BASED HYPERTROPHY EXERCISE CORE (FAZ 7)
================================================
'Saçma dataset' senaryosunun çözümü: 600+ ham parquet kaydının üzerine, her kas
grubunun TÜM başlarını (heads) ve direnç profillerini kapsayan KÜRATÖRLÜ bilimsel
çekirdek. seed_knowledge bu listeyi idempotent olarak exercise_library_items
tablosuna yazar; parquet kayıtlarıyla birlikte yaşar ama select_rank'te üstte durur.

Her kayıt için:
  stimulus_rating (0-10): literatür destekli hipertrofi uyarım puanı
  muscle_head: kasın hangi bölümünü öncelikli yüklediği
  rom_profile: full | lengthened | shortened | partial | isometric
  evidence_refs: BOŞ - hiçbir PMID elle yazılmaz, verify_pmid.py doğrular.
  selection_reason: kısaltmadan bilimsel gerekçe (EMG/hipertrofi çalışma temelli)

Bilimsel dayanak prensipleri:
  1. Lengthened-state overload: kasın gerilmiş pozisyonda yük aldığı hareketler
     öncelikli (Maeo 2021/2023, Pedrosa 2022, Wolf 2023 çizgisi).
  2. Her kas için compound + lengthened izolasyon + shortened izolasyon üçlüsü.
  3. Agonist-izole yüklemede baş ayrımı (long head / lateral head / upper / lower...).
  4. 6-12 genel, 12-20 yüksek-hacim izolasyon rep bias kuralı.
"""
from __future__ import annotations

# (name, aliases, muscle_group, exercise_type, stretch_mediated, unilateral,
#  equipment, technique_cue, rep_range_bias, contraindications, muscle_head,
#  stimulus_rating, rom_profile, difficulty, force_type, mechanic,
#  goals, selection_reason)
EVIDENCE_EXERCISES: list[tuple] = [
    # ---------------- GÖĞÜS ----------------
    ("Incline Dumbbell Press", "Eğimli Dambbell Press, Incline DB Press", "Göğüs",
     "primary_compound", False, False, "dumbbell",
     "30-45° eğim, dambılları kontrollü indir, kürek kemiklerini sabitle", "6-10", "shoulder",
     "upper", 8.8, "full", "beginner", "push", "compound",
     "hypertrophy|strength",
     "Üst göğüs için yüklenebilir bileşik varyant; kullanıcı deneyimi ve omuz toleransına göre barbell alternatifi."),
    ("Incline Barbell Bench Press", "Eğimli Barbell Bench, Upper Bench", "Göğüs",
     "primary_compound", False, False, "barbell",
     "30-45° eğim, çubuk klavikula hattına insin, kürek kemikleri geri-aşağı", "6-10", "",
     "upper", 9.0, "full", "intermediate", "push", "compound",
     "hypertrophy|strength",
     "Üst göğüs (clavicular) fiberlerine en yüksek gerilim; incline açısı omuz yükünü azaltır ve üst başı hedefler."),
    ("Flat Dumbbell Press", "Düz Dambıl Bench, DB Press", "Göğüs",
     "primary_compound", False, False, "dumbbell",
     "Dirsekler 45-75°, kürek kemikleri yastığa yaslı, tam göğüs teması", "6-10", "",
     "overall", 9.0, "full", "beginner", "push", "compound",
     "hypertrophy",
     "Geniş hareket aralığı flat press; göğsün genel (sternal+clavicular) yüklenmesi için en yüksek toplam kaldırılabilir ağırlık."),
    ("Incline Dumbbell Fly", "Eğimli Dambıl Fly, DB Fly", "Göğüs",
     "stretch_isolation", True, False, "dumbbell",
     "Elleri derin aç, göğüste maksimum gerilme hisset, kürek kemikleri yapışık", "10-15", "shoulder",
     "upper", 9.2, "lengthened", "intermediate", "push", "isolation",
     "hypertrophy",
     "Omuz ekstansiyonda göğüs tam gerilmiş pozisyonda yüklenir (lengthened-state overload); üst göğüs başı için en güçlü izolasyon."),
    ("Cable Crossover", "Kablolu Çapraz, Cable Fly", "Göğüs",
     "stretch_isolation", True, False, "cable",
     "Kollar yukarıdan aşağı süpürürken göğsü sık, tepe noktada 1 sn kontraksiyon", "12-15", "shoulder",
     "overall", 8.8, "lengthened", "intermediate", "push", "isolation",
     "hypertrophy",
     "Tüm ROM boyunca sabit kablo direnci; gerilmiş pozisyonda göğüs fiberlerini maksimum süre gerimde tutar."),
# ---------------- SIRT (LAT + ORTA + ÜST) ----------------
    ("Weighted Pull-up", "Ağırlıklı Barfiks, Pull-up", "Sırt",
     "primary_compound", True, False, "bodyweight",
     "Kürek kemiklerini aşağı çek, göğsü bara yaklaştır, tam iniş", "6-10", "",
     "lat_lower", 9.4, "lengthened", "intermediate", "pull", "compound",
     "hypertrophy|strength",
     "Lat'ın en uzun gerilmiş pozisyonunda (omuz tam fleksiyon) ağırlık eklenebilen en güçlü dikey bileşik; lengthened overload kuralı."),
    ("Lat Pull-down", "Kablolu Öne Çekiş, Pull-down", "Sırt",
     "secondary_compound", True, False, "cable",
     "Göğsü bara yaklaştır, kollarla değil kürekle çek, tepe noktada sık", "8-12", "",
     "lat_upper", 8.6, "lengthened", "beginner", "pull", "compound",
     "hypertrophy",
     "Pull-up'a giriş varyasyonu; üst lat fiberlerini gerilmiş pozisyonda yükler, yük kontrolü tam."),
    ("Straight-Arm Pullover", "Düz Kol Pullover, Pullover", "Sırt",
     "stretch_isolation", True, False, "cable",
     "Kollar düz, başın arkasına kadar götür, lat gerilmesini hisset", "10-15", "",
     "lat_lower", 8.9, "lengthened", "intermediate", "pull", "isolation",
     "hypertrophy",
     "Omuz tam fleksiyonunda lat en uzun pozisyonda yüklenir; lat'ı izole çalıştıran saf lengthened izolasyon."),
    ("Chest-Supported Row", "Göğüs Destekli Row, Incline DB Row", "Sırt",
     "secondary_compound", False, False, "machine",
     "Göğüs pedala yapışık, kürek kemiklerini sıkıştır, omuzları geriye indir", "10-12", "",
     "mid_back", 8.2, "full", "beginner", "pull", "compound",
     "hypertrophy",
     "Bel yükü olmadan orta sırt (rhomboid/trapezius) hacmi; ağır kürek için güvenli yüklenme."),
    ("Seated Cable Row", "Oturarak Kablo Çekiş, Cable Row", "Sırt",
     "secondary_compound", False, False, "cable",
     "Gövde sabit, kürekle çek, göğüs dışa açık, sırtta sıkıştır", "8-12", "",
     "mid_back", 8.4, "full", "beginner", "pull", "compound",
     "hypertrophy",
     "Tek düzlemde sabit direnç; orta sırt kalınlığı ve rhomboid gelişimi için temel yatay bileşik."),
    ("Single-Arm Dumbbell Row", "Tek Kol Dambıl Row, DB Row", "Sırt",
     "secondary_compound", False, True, "dumbbell",
     "Destek eli bench'te, dirseği bele çek, sırtta kontraksiyon", "10-12", "lower_back",
     "lat_upper", 8.4, "full", "beginner", "pull", "compound",
     "hypertrophy",
     "Tek taraflı ağır kürek; asimetri düzeltir, hareket aralığını maksimize eder, lat ve orta sırtı eşit yükler."),
    ("Rack Pulls", "Rack Pulls, Kısmi Deadlift", "Sırt",
     "primary_compound", False, False, "barbell",
     "Bar diz hizasında, kalça geri, sırt düz, dikleşirken sıkıştır", "5-8", "lower_back",
     "upper_traps", 7.6, "partial", "intermediate", "pull", "compound",
     "strength",
     "Üst trapezius ve erektör için kısmi ROM'lu ağır yükleme; güç fazı için serbest ağırlık varyantı."),
    ("Reverse Pec Deck", "Ters Pec Deck, Rear Delt Fly", "Sırt",
     "stretch_isolation", True, False, "machine",
     "Kollar geride aç, arka delt ve orta sırt sıkıştırması, 1 sn tut", "12-15", "shoulder",
     "rear_delt", 8.0, "lengthened", "beginner", "pull", "isolation",
     "hypertrophy",
     "Omuz ekstansiyonda arka delt + rhomboid tam gerilmiş pozisyonda izole yük; posterior dengesi."),
    ("Face Pull", "Yüz Çekişi, Face Pull", "Sırt",
     "stretch_isolation", True, False, "cable",
     "Halatı yüz hizasına çek, dirsekler yukarı, dış rotasyonu hisset", "12-20", "shoulder",
     "rear_delt", 7.8, "lengthened", "beginner", "pull", "isolation",
     "rehab|hypertrophy",
     "Arka delt + rotator cuff dış rotatorlarını yüksek tekrarlı izole çalıştırır; omuz sağlığı prehab."),
    # ---------------- QUADRICEPS ----------------
    ("ATG Back Squat", "Derin Squat, ATG Squat", "Quadriceps",
     "primary_compound", False, False, "barbell",
     "ATG derinlik, dizler ayak yönünde, kalça dizden aşağı inmez, dik gövde", "6-10", "knee",
     "overall", 9.4, "full", "intermediate", "push", "compound",
     "hypertrophy|strength",
     "Derinlikte quadriceps fiberleri tam gerilim ve en yüksek kadansa ulaşır; squat derinliği quad hipertrofisi ile doğru orantılı."),
    ("Front Squat", "Öne Squat, Front Squat", "Quadriceps",
     "primary_compound", False, False, "barbell",
     "Dirsekler yukarı, bar omuz önünde, kalça dizle birlikte aşağı", "6-10", "knee|wrist",
     "overall", 9.0, "full", "intermediate", "push", "compound",
     "hypertrophy",
     "Gövde daha dik tutulduğundan quadriceps'e daha fazla moment yükü biner; derin squatta quad vurgusu maksimal."),
    ("Hack Squat (Deep)", "Hack Squat Makinesi, Derin Hack", "Quadriceps",
     "secondary_compound", False, False, "machine",
     "Sırt yastığa yapışık, derin in, dizleri göğse yaklaştır", "8-12", "knee",
     "overall", 8.6, "full", "beginner", "push", "compound",
     "hypertrophy",
     "Serbest denge gerektirmeyen derin quad yüklemesi; yüksek hacimli quad gelişimi için makine stabilizasyonu."),
    ("Bulgarian Split Squat", "Bulgarian Split Squat, Derin Split", "Quadriceps",
     "secondary_compound", True, True, "dumbbell",
     "Arka ayak yüksek, ön diz üstüne insin, ön bacak dikey kalsın", "8-12", "knee",
     "rectus_femoris", 9.0, "lengthened", "intermediate", "push", "compound",
     "hypertrophy",
     "Kalça fleksiyon + diz fleksiyon derinliğinde rectus femoris tam gerilmiş pozisyonda yüklenir; unilateral denge."),
    ("Leg Press (Deep)", "Bacak Press, Derin Leg Press", "Quadriceps",
     "secondary_compound", False, False, "machine",
     "Dizleri göğse yaklaştır (derin), kontrollü it", "10-15", "knee",
     "overall", 8.4, "full", "beginner", "push", "compound",
     "hypertrophy",
     "Çok yüksek hacimde derin quad yüklemesi yapılabilir; derin pozisyonda quad fiberleri uzun boyda gerilir."),
    ("Sissy Squat", "Sissy Squat", "Quadriceps",
     "stretch_isolation", True, False, "bodyweight",
     "Gövde geriye, dizler ileri; quad tam gerilmede, diz ekstansör izolasyonu", "10-15", "knee",
     "vastus_medialis", 8.0, "lengthened", "advanced", "push", "isolation",
     "hypertrophy",
     "Quadriceps'i kısalan değil GERİLEN uzun pozisyonda izole yükler; vastus medialis gelişimi için lengthened varyant."),
    ("Leg Extension", "Bacak Üstü, Quad Extension", "Quadriceps",
     "shortened_isolation", False, False, "machine",
     "Uzatma pozisyonunda 1 sn tepe sıkıştırması, kontrollü iniş", "12-20", "knee",
     "vastus_medialis", 8.2, "shortened", "beginner", "push", "isolation",
     "hypertrophy",
     "Kısalan pozisyonda (distal) quad izolasyonu; üçlü kurulumun (compound + lengthened + shortened) son halkası."),
    # ---------------- HAMSTRING & GLUTE ----------------
    ("Romanian Deadlift", "RDL, Deadlift Rumen", "Hamstring & Glute",
     "primary_compound", True, False, "barbell",
     "Dizler hafif bükük, kalça geriye, hamstring gerilimini hisset, bar bacağa yakın", "6-10", "lower_back",
     "biceps_femoris", 9.2, "lengthened", "intermediate", "pull", "compound",
     "hypertrophy|strength",
     "Kalça fleksiyonunda biceps femoris long head en uzun pozisyonda yüklenir; hamstring lengthened overload'ın altın standardı."),
    ("Seated Leg Curl", "Oturarak Bacak Curl, Seated Hamstring", "Hamstring & Glute",
     "stretch_isolation", True, False, "machine",
     "Ağırlığı kontrollü bırak, kalça fleksiyonda hamstring tam gerilmesini hisset", "10-15", "knee",
     "biceps_femoris", 9.0, "lengthened", "intermediate", "pull", "isolation",
     "hypertrophy",
     "Kalça 90° fleksiyonda hamstring GERİLİR; seated curl'un lengthened pozisyonu, yalancı (lying) curl'a hipertrofi için belirgin üstündür."),
    ("Lying Leg Curl", "Yüzüstü Bacak Curl, Lying Hamstring", "Hamstring & Glute",
     "secondary_compound", False, False, "machine",
     "Topuğu kalçaya çek, tepe noktada sık, kontrollü aç", "10-12", "knee",
     "semitendinosus", 8.0, "shortened", "beginner", "pull", "isolation",
     "hypertrophy",
     "Kalça ekstansiyonda hamstring kısalan pozisyonda çalışır; medial (iç) hamstring başı vurgusu."),
    ("Hip Thrust", "Kalça İtişi, Hip Thrust", "Hamstring & Glute",
     "primary_compound", False, False, "barbell",
     "Çene içeride, kalçayı yukarı it, tepe noktada 1 sn glute sıkıştırması", "8-12", "lower_back",
     "gluteus_maximus", 9.2, "full", "intermediate", "push", "compound",
     "hypertrophy",
     "Gluteus maximus'u en yüksek aktivasyonla çalıştıran bileşik; kalça ekstansiyon yönünde maksimum gerilim."),
    ("45-Degree Hyperextension", "Hiperekstansiyon, 45° Back Extension", "Hamstring & Glute",
     "secondary_compound", True, False, "bodyweight",
     "Omurgayı nötral tut, derin fleksiyonda hamstring-erektor gerilmesi hisset", "10-15", "lower_back",
     "gluteus_maximus", 8.2, "lengthened", "beginner", "pull", "compound",
     "hypertrophy",
     "Kalça tam fleksiyonda hamstring ve glute gerilmiş pozisyonda; lengthened blok için ideal tamamlayıcı."),
    ("Sumo Deadlift", "Sumo Deadlift", "Hamstring & Glute",
     "primary_compound", False, False, "barbell",
     "Geniş duruş, dizler dışa, kalça derin, sırt düz, barı vücuda yakın kaldır", "5-8", "lower_back",
     "gluteus_maximus", 8.6, "full", "advanced", "pull", "compound",
     "strength|hypertrophy",
     "Geniş duruş medial glutelere ve addüktörlere daha fazla yük bindirir; hamstring+glute bileşik güç kaynağı."),
    ("Cable Kickback", "Kablo Kickback, Glute Kickback", "Hamstring & Glute",
     "stretch_isolation", True, False, "cable",
     "Bacağı arkaya-yukarı it, glute tepe kasılmasını hisset", "12-15", "",
     "gluteus_maximus", 7.8, "lengthened", "beginner", "push", "isolation",
     "hypertrophy",
     "Kalça ekstansiyon yönünde glute tam gerilmiş pozisyondan kısalan pozisyona izole yüklenir."),
    # ---------------- OMUZ (DELTOİD) ----------------
    ("Overhead Barbell Press", "Askeri Press, Militar Press", "Omuz",
     "primary_compound", False, False, "barbell",
     "Bar göğüs üstünde, glute sıkı, çubuğu baş üstüne it, çene geri", "6-10", "shoulder",
     "anterior|lateral", 8.8, "full", "intermediate", "push", "compound",
     "hypertrophy|strength",
     "Anterior ve lateral deltoid bileşik yük; en yüksek toplam omuz yüklenebilen serbest ağırlık hareketi."),
    ("Dumbbell Shoulder Press", "Dambıl Shoulder Press", "Omuz",
     "secondary_compound", False, False, "dumbbell",
     "Dambıllar kulak hizasına inebilir, yukarıda dirsekleri kilitleme", "8-12", "shoulder",
     "anterior|lateral", 8.6, "full", "beginner", "push", "compound",
     "hypertrophy",
     "Dambıl, bar'a göre daha derin gerilme ve bağımsız kol hareketi sağlar; omuz asimetrisini düzeltir."),
    ("Cable Lateral Raise", "Kablo Lateral Raise, Yan Omuz Kablo", "Omuz",
     "stretch_isolation", True, False, "cable",
     "Kolu yataydan biraz yukarı aç, serçe parmak yukarı bakar, tepe noktada 1 sn", "12-15", "shoulder",
     "lateral", 9.2, "lengthened", "intermediate", "push", "isolation",
     "hypertrophy",
     "Kablo ile yük en zayıf (başlangıç) pozisyonda olur; lateral deltoidi gerilmiş pozisyonda yükler, orta omuz genişliği için en güçlü izolasyon."),
    ("Lean-Away Lateral Raise", "Lean-Away Lateral, Eğik Yan Raise", "Omuz",
     "stretch_isolation", True, False, "dumbbell",
     "Gövde dambıldan uzağa eğik, kolu vücudun arkasında çapraz aç", "12-15", "shoulder",
     "lateral", 8.8, "lengthened", "intermediate", "push", "isolation",
     "hypertrophy",
     "Eğilme ile adduksiyonun en zayıf noktası ele alınır; lateral baş orta pozisyonunda tam ROM gerilimi."),
    ("Behind-the-Back Cable Lateral", "Arkadan Kablo Lateral, Y Cable", "Omuz",
     "stretch_isolation", True, False, "cable",
     "Vücut önünde çapraz tut, dışa-aşağı aç, arka yan baş gerilmesini hisset", "12-15", "shoulder",
     "posterior_lateral", 8.2, "lengthened", "intermediate", "push", "isolation",
     "hypertrophy",
     "Omuzun arka potansiyelinde başlangıç pozisyonunda yük verir; arka-lateral başı uzun boyda izole yükler."),
    ("Reverse Pec Deck (Rear Delt)", "Ters Pec Deck, Omuz Arka", "Omuz",
     "stretch_isolation", True, False, "machine",
     "Kollar açık, arka delti sıkıştır, 1 sn tut", "12-15", "shoulder",
     "posterior", 8.2, "lengthened", "beginner", "pull", "isolation",
     "hypertrophy",
     "Omuz abduksiyonda arka deltoid tam gerilmiş pozisyonda izole yük; posterior omuz dengesinin çekirdeği."),
("Face Pull (Cable)", "Yüz Çekişi, Face Pull Omuz", "Omuz",
     "stretch_isolation", True, False, "cable",
     "Halatı yüz hizasına çek, dış rotasyonla aç", "15-20", "shoulder",
     "posterior", 7.8, "lengthened", "beginner", "pull", "isolation",
     "rehab|hypertrophy",
     "Arka delt + rotator cuff prehab; dış rotatörlerde yüksek tekrar dayanıklılığı ve omuz sağlığı."),
    # ---------------- BICEPS ----------------
    ("Incline Dumbbell Curl", "Eğimli Dambıl Curl, Incline DB Curl", "Biceps",
     "stretch_isolation", True, False, "dumbbell",
     "Kol arkada serbest sarkar, omuz ekstansiyonda biceps tam gerilir, kontrollü kıvır", "10-12", "",
     "long_head", 9.0, "lengthened", "intermediate", "pull", "isolation",
     "hypertrophy",
     "Omuz ekstansiyonda biceps long head en uzun gerilmiş pozisyonda yüklenir; bayesian curl'ün temeli."),
    ("Bayesian Cable Curl", "Bayesian Curl, Kablo Uzun Baş Curl", "Biceps",
     "stretch_isolation", True, False, "cable",
     "Kol arkada, kablo ile omuz ekstansiyondan başla, tepe noktada sık", "12-15", "",
     "long_head", 8.8, "lengthened", "intermediate", "pull", "isolation",
     "hypertrophy",
     "Kablo sabit direnci ile uzun pozisyonda biceps long head izole; tepe noktada maksimal kontraksiyon."),
    ("EZ Bar Curl", "EZ Bar Biceps Curl", "Biceps",
     "secondary_compound", False, False, "barbell",
     "Dirsekleri sabit, barı omuza kıvır, negatifi 2-3 sn kontrol", "8-12", "wrist",
     "short_head", 8.0, "shortened", "beginner", "pull", "compound",
     "hypertrophy",
     "Kısa başa maksimum yük bindiren en ağır kaldırılabilir curl varyantı; toplam hacim ve güç kaynağı."),
    ("Preacher Curl", "Preacher Curl, Scott Curl", "Biceps",
     "shortened_isolation", False, False, "machine",
     "Kol tam uzar, yastığa sabit, dirsek destekli - hile yapma", "10-12", "wrist",
     "short_head", 7.8, "shortened", "beginner", "pull", "isolation",
     "hypertrophy",
     "Sabit dirsek pozisyonunda kısa baş izolasyonu; tepe nokta gerilimi ve kontrollü negatif ile kol kalınlığı."),
    ("Hammer Curl", "Çekiç Curl, Hammer Curl", "Biceps",
     "shortened_isolation", False, False, "dumbbell",
     "Nötral tutuş, dambılı omuza kıvır, brachialis-brachioradialis odaklı", "10-12", "",
     "brachialis", 7.6, "shortened", "beginner", "pull", "isolation",
     "hypertrophy",
     "Nötral tutuş ile brachialis ve brachioradialis'i izole yükler; kolun genel kalınlık görünümü için."),
    ("Spider Curl", "Spider Curl, Öne Eğik Curl", "Biceps",
     "stretch_isolation", True, False, "dumbbell",
     "Gövde öne eğik, kol dikey sarkar, omuz fleksiyonda long head geriliminde kıvır", "12-15", "",
     "long_head", 8.2, "lengthened", "intermediate", "pull", "isolation",
     "hypertrophy",
     "Gövde eğikliği omuzu fleksiyona alır; biceps long head tam gerilmiş pozisyonda izole çalışır."),
    # ---------------- TRICEPS ----------------
    ("Overhead Cable Triceps Extension", "Üstten Kablo Triceps, Overhead Extension", "Triceps",
     "stretch_isolation", True, False, "cable",
     "Dirsekleri yukarıda sabit tut, halatı başın arkasında tam ger, tepe noktada sık", "10-15", "shoulder",
     "long_head", 9.2, "lengthened", "intermediate", "push", "isolation",
     "hypertrophy",
     "Omuz tam fleksiyonda triceps long head en uzun gerilmiş pozisyonda yüklenir; long head kütlesi için literatürde öne çıkan hareket."),
    ("Overhead Dumbbell Extension", "Üstten Dambıl Extension, French Press", "Triceps",
     "stretch_isolation", True, False, "dumbbell",
     "Dambılı başın arkasına derin indir, dirsekler içe dönük, tam gerilme hisset", "10-12", "shoulder",
     "long_head", 8.8, "lengthened", "intermediate", "push", "isolation",
     "hypertrophy",
     "Tam gerilmiş pozisyonda long head yüklemesi; French press uzun baş kütlesinin klasik izolasyonu."),
    ("Cable Triceps Pushdown", "Kablo Pushdown, Triceps Aşağı", "Triceps",
     "shortened_isolation", False, False, "cable",
     "Dirsekler gövdeye sabit, aşağıda kolları tam kilitle, 1 sn sık", "12-15", "",
     "lateral_head", 8.4, "shortened", "beginner", "push", "isolation",
     "hypertrophy",
     "Dirsek ekstansiyonun kısalma yönünde lateral ve medial başı izole yükler; yüksek hacimli kol bitirici."),
    ("Close-Grip Bench Press", "Dar Tutuş Bench, CG Bench", "Triceps",
     "primary_compound", False, False, "barbell",
     "Eller omuz genişliğinde, dirsekler gövdeye yakın, barı göğse indir", "6-10", "wrist|shoulder",
     "overall", 8.8, "full", "intermediate", "push", "compound",
     "hypertrophy|strength",
     "Triceps'e en yüksek eksternal yük bindiren bileşik; genel kol kütlesi ve itiş gücü için temel."),
    ("Diamond Push-up", "Elmas Şınav, Diamond Push-up", "Triceps",
     "secondary_compound", False, False, "bodyweight",
     "Eller elmas pozisyonunda, göğsü ellere indir, dirsekler içe", "10-20", "wrist",
     "medial_head", 7.6, "full", "beginner", "push", "compound",
     "hypertrophy",
     "Dar tutuş ile triceps (özellikle medial baş) bileşik vücut ağırlığı yüklemesi; ev antrenmanı için ideal."),
    ("Skull Crusher", "Skull Crusher, Lying Triceps Extension", "Triceps",
     "stretch_isolation", True, False, "barbell",
     "Barı alnın üstüne indir, dirsekler sabit, tam frontal gerilme", "10-12", "elbow",
     "long_head", 8.4, "lengthened", "intermediate", "push", "isolation",
     "hypertrophy",
     "Omuz fleksiyonda long head gerilmiş pozisyonda + dirsek ekstansiyon kombinasyonu; uzun baş kütlesi için tamamlayıcı."),
    ("Triceps Machine Dip", "Triceps Dip Makinesi, Assisted Dip", "Triceps",
     "secondary_compound", False, False, "machine",
     "Dirsekler geride, gövde dik, derine in, triceps gerilmesini hisset", "10-15", "shoulder",
     "long_head", 7.8, "lengthened", "beginner", "push", "compound",
     "hypertrophy",
     "Destekli dip omuz ekstansiyonunda long head'ı gerilmiş pozisyonda yükler; yeni başlayan için güvenli giriş."),
    # ---------------- KARIN (CORE) ----------------
    ("Hanging Leg Raise", "Asılı Bacak Kaldırma, Hanging Raise", "Karın",
     "stretch_isolation", True, False, "bodyweight",
     "Leğen kemiğini yukarı yuvarla, bacakları kontrolle indir, beli bükme", "10-15", "grip",
     "lower_abs", 8.8, "lengthened", "intermediate", "pull", "isolation",
     "hypertrophy",
     "Rektus abdominis alt başı gerilmiş pozisyonda; gerilim pelvisin yukarı yuvarlanmasından gelir."),
    ("Ab Wheel Rollout", "Ab Wheel, Tekerlek Çekme", "Karın",
     "secondary_compound", True, False, "bodyweight",
     "Kalçayı öne çıkar, omurgayla yuvarlanma, derin gerilmede 1 sn bekle", "8-15", "lower_back",
     "overall", 9.0, "lengthened", "intermediate", "push", "compound",
     "hypertrophy",
     "Rektus abdominis'i hem gerilmiş pozisyonda hem dinamik olarak yükler; core gerilim profili ve karın kalınlığı için en güçlü hareket."),
    ("Weighted Cable Crunch", "Kablo Crunch, Ağırlıklı Karın Bükme", "Karın",
     "shortened_isolation", False, False, "cable",
     "Torakal bölgeden bük, kaburgaları kalçaya yaklaştır, tepe noktada sık", "12-20", "",
     "upper_abs", 8.4, "shortened", "beginner", "pull", "isolation",
     "hypertrophy",
     "Rektus abdominis üst başına kısalma yönünde eksternal yük; ağırlığı düzenli artırılabilir."),
    ("Pallof Press", "Pallof Press, Kablo Anti-Rotasyon", "Karın",
     "core_prehab", False, False, "cable",
     "Kabloyu göğüste tut, iki elle öne it, gövdeyi dönmeye karşı sabit tut", "12-20", "",
     "obliques", 7.8, "isometric", "beginner", "push", "core_prehab",
     "rehab|hypertrophy",
     "Oblikleri izometrik anti-rotasyon yüküyle çalıştırır; bel omurgasını koruyan derin core dengesi."),
    ("Side Plank (Weighted)", "Yan Plank, Ağırlıklı Side Plank", "Karın",
     "core_prehab", False, False, "bodyweight",
     "Dirsek omuz altında, kalça yukarı, gövde düz çizgide", "30-60sn", "shoulder",
     "obliques", 7.4, "isometric", "beginner", "static", "core_prehab",
     "rehab",
     "Quadratus lumborum ve oblikleri izometrik yükler; bel ve core stabilizasyon prehab."),
    # ---------------- BALDIR ----------------
    ("Standing Calf Raise", "Ayakta Baldır Kaldırma, Standing Calf", "Baldır",
     "stretch_isolation", True, False, "machine",
     "Topuklar en derine in (ayak bileği dorsifleksiyon), en tepe noktada 1 sn", "10-15", "",
     "gastrocnemius", 8.6, "lengthened", "beginner", "push", "isolation",
     "hypertrophy",
     "Gastrocnemius'u diz ekstansiyonda gerilmiş pozisyondan yükler; en uzun gerilim aralığında ayakta izolasyon."),
    ("Seated Calf Raise", "Oturarak Baldır Kaldırma, Seated Calf", "Baldır",
     "stretch_isolation", True, False, "machine",
     "Diz 90° fleksiyonda, topuğu en derine indir, tepe noktada sık", "12-20", "",
     "soleus", 8.2, "lengthened", "beginner", "push", "isolation",
     "hypertrophy",
     "Diz fleksiyonunda gastrocnemius pasif kalır, soleus tam gerilmiş pozisyonda izole yüklenir."),
    ("Single-Leg Calf Raise", "Tek Bacak Baldır, Bulgarian Calf", "Baldır",
     "stretch_isolation", True, True, "dumbbell",
     "Tek bacak denge, tam dorsifleksiyonda topuğu derine indir", "12-15", "",
     "gastrocnemius", 8.0, "lengthened", "intermediate", "push", "isolation",
     "hypertrophy",
     "Tek taraflı yük ile asimetriyi düzeltir, gastrocnemius'u unilateral tam gerilmede çalıştırır."),
    ("Leg Press Calf Raise", "Bacak Press Baldır, Press Calf", "Baldır",
     "secondary_compound", False, False, "machine",
     "Topukları platform kenarına al, ayak parmaklarıyla it-ger", "12-20", "",
     "gastrocnemius|soleus", 7.8, "full", "beginner", "push", "compound",
     "hypertrophy",
     "Bacak press yüklenmesiyle baldıra yüksek hacimli direnç; gezici ayak açısı ile baş vurgusu değiştirilir."),
    # ---------------- KONTROLLÜ EK KAPSAM (ekipman/ev varyantları) ----------------
    ("Push-Up", "Şınav, Push Up", "Göğüs",
     "secondary_compound", True, False, "bodyweight",
     "Gövde düz, göğsü kontrollü indir, kürek kemiklerini serbestçe hareket ettir", "8-20", "shoulder|wrist",
     "overall", 8.0, "lengthened", "beginner", "push", "compound",
     "hypertrophy",
     "Ekipmansız göğüs ve itiş hacmi; yük, tekrar veya mekanik dezavantajla kademeli artırılabilir."),
    ("Machine Chest Press", "Makine Chest Press, Chest Press Machine", "Göğüs",
     "secondary_compound", False, False, "machine",
     "Kürek kemiklerini destekle, tutacakları kontrollü indir, tam itişte dirsekleri kilitleme", "8-15", "shoulder",
     "overall", 8.3, "full", "beginner", "push", "compound",
     "hypertrophy",
     "Stabil gövde desteğiyle göğüs hacmini güvenilir biçimde ölçekler; serbest ağırlık gerektirmeden yakın efora ulaşmayı kolaylaştırır."),
    ("Cable Chest Press", "Kablo Göğüs Press, Standing Cable Press", "Göğüs",
     "secondary_compound", False, True, "cable",
     "Kabloları göğüs hizasından ileri it, gövdeyi sabit tut, kontrollü geri dön", "10-15", "shoulder",
     "overall", 8.1, "full", "beginner", "push", "compound",
     "hypertrophy",
     "Tek taraflı veya çift taraflı sabit direnç seçeneği; göğüs hacmini ekipman ve omuz toleransına göre ayarlar."),
    ("Machine Lat Pulldown", "Makine Lat Pulldown, Lat Pulldown Machine", "Sırt",
     "secondary_compound", True, False, "machine",
     "Kolları yukarıda tamamen uzat, dirsekleri kaburgalara doğru çek, gövdeyi sallama", "8-15", "shoulder",
     "lat_upper", 8.5, "lengthened", "beginner", "pull", "compound",
     "hypertrophy",
     "Dikey çekişte yükü ve hareket açıklığını kolay ayarlatır; latların uzun pozisyondaki yüklenmesini destekler."),
    ("One-Arm Cable Row", "Tek Kol Kablo Row, Single-Arm Cable Row", "Sırt",
     "secondary_compound", False, True, "cable",
     "Omuzu öne kontrollü bırak, dirseği kalçaya çek, gövdeyi döndürme", "10-15", "lower_back",
     "lat_upper", 8.3, "full", "beginner", "pull", "compound",
     "hypertrophy",
     "Tek taraflı yatay çekiş; hareket açıklığı ve taraflar arası yük farkını yönetmek için kullanılır."),
    ("Dumbbell Pullover", "Dambıl Pullover, DB Pullover", "Sırt",
     "stretch_isolation", True, False, "dumbbell",
     "Dambılı başın arkasına kontrollü indir, kaburgaları açmadan lat gerilimini koru", "10-15", "shoulder",
     "lat_lower", 7.8, "lengthened", "intermediate", "pull", "isolation",
     "hypertrophy",
     "Omuz fleksiyonunda latlara uzun pozisyon yükü sağlar; omuz toleransı uygun kişilerde dikey çekişi tamamlar."),
    ("Goblet Squat", "Goblet Squat, Kettlebell Goblet Squat", "Quadriceps",
     "secondary_compound", False, False, "dumbbell",
     "Ağırlığı göğüste tut, gövdeyi dikleştir, ağrısız derinliğe kontrollü in", "10-15", "knee",
     "overall", 8.1, "full", "beginner", "push", "compound",
     "hypertrophy",
     "Yeni başlayan ve ev ekipmanı kullanan kişiler için dengesi kolay derin squat seçeneği; quad hacmini ilerletmeye uygundur."),
    ("Smith Machine Squat", "Smith Squat, Smith Machine Squat", "Quadriceps",
     "secondary_compound", False, False, "machine",
     "Ayak konumunu sabitle, ağrısız derinliğe in, dizleri ayak yönünde takip ettir", "8-12", "knee",
     "overall", 8.4, "full", "beginner", "push", "compound",
     "hypertrophy",
     "Bar yolu sabit olduğu için quad setlerini denge sınırlamasını azaltarak tekrarlanabilir biçimde yükler."),
    ("Dumbbell Romanian Deadlift", "Dambıl RDL, DB Romanian Deadlift", "Hamstring & Glute",
     "primary_compound", True, False, "dumbbell",
     "Kalçayı geriye gönder, dambılları bacağa yakın tut, hamstring gerilimi bitmeden kalk", "8-12", "lower_back",
     "biceps_femoris", 8.7, "lengthened", "beginner", "pull", "compound",
     "hypertrophy",
     "Barbell RDL'ye erişimi olmayanlarda kalça menteşesini ve hamstringin uzun pozisyon yükünü koruyan seçenek."),
    ("Glute Bridge", "Glute Bridge, Kalça Köprüsü", "Hamstring & Glute",
     "shortened_isolation", False, False, "bodyweight",
     "Kaburgaları aşağıda tut, kalçayı yukarı sık, belden aşırı yaylanma", "12-20", "lower_back",
     "gluteus_maximus", 7.9, "shortened", "beginner", "push", "isolation",
     "hypertrophy",
     "Ekipmansız kalça ekstansiyonu; glute kasılma ucunda hacim ve aktivasyon çalışması için erişilebilir tamamlayıcı."),
    ("Machine Hip Thrust", "Makine Hip Thrust, Glute Drive", "Hamstring & Glute",
     "primary_compound", False, False, "machine",
     "Pelvisi nötrleştir, üstte kalçayı sık, kontrollü başlangıca dön", "8-15", "lower_back",
     "gluteus_maximus", 8.6, "full", "beginner", "push", "compound",
     "hypertrophy",
     "Makine desteğiyle gluteus maximus için tekrarlanabilir kalça ekstansiyonu ve yük ilerlemesi sağlar."),
    ("Dumbbell Lateral Raise", "Dambıl Yan Raise, DB Lateral Raise", "Omuz",
     "stretch_isolation", True, False, "dumbbell",
     "Dirsekleri hafif kır, kolu omuz hizasına kontrollü aç, gövdeyi sallama", "12-20", "shoulder",
     "lateral", 8.5, "lengthened", "beginner", "push", "isolation",
     "hypertrophy",
     "Lateral deltoid için basit ve erişilebilir izolasyon; yükü küçük artışlarla ve kontrollü ROM ile ilerletmek kolaydır."),
    ("Machine Shoulder Press", "Makine Shoulder Press, Shoulder Press Machine", "Omuz",
     "secondary_compound", False, False, "machine",
     "Kürek kemiklerini pedala yasla, tutacakları kontrollü indir, ağrısız ROM kullan", "8-12", "shoulder",
     "anterior|lateral", 8.2, "full", "beginner", "push", "compound",
     "hypertrophy",
     "Gövde desteğiyle anterior ve lateral deltoid yükünü tekrarlanabilir biçimde artırır; stabilizasyon maliyetini düşürür."),
    ("Cable Rear Delt Fly", "Kablo Arka Omuz Fly, Cable Reverse Fly", "Omuz",
     "stretch_isolation", True, True, "cable",
     "Kolları çaprazdan dışa aç, omuzları yukarı çekme, arka delti kontrollü sık", "12-20", "shoulder",
     "posterior", 8.1, "lengthened", "beginner", "pull", "isolation",
     "hypertrophy",
     "Arka deltoidi tek veya çift taraflı sabit dirençle izole eder; omuz dengesi için düşük yorgunluklu seçenek."),
    ("Cable Hammer Curl", "Kablo Hammer Curl, Rope Hammer Curl", "Biceps",
     "shortened_isolation", False, False, "cable",
     "Nötral tutuşu koru, dirsekleri sabit tut, kontrollü eksantrik uygula", "10-15", "wrist",
     "brachialis", 8.0, "full", "beginner", "pull", "isolation",
     "hypertrophy",
     "Nötral tutuşla brachialis ve brachioradialis'i çalıştırır; kablo direnci boyunca düzenli yük sunar."),
    ("Machine Biceps Curl", "Makine Biceps Curl, Biceps Curl Machine", "Biceps",
     "shortened_isolation", False, False, "machine",
     "Üst kolu pedala sabitle, tam kontrollü aç-kapa, omuzu öne yuvarlama", "10-15", "wrist",
     "short_head", 8.0, "shortened", "beginner", "pull", "isolation",
     "hypertrophy",
     "Sabit üst kol desteğiyle biceps izolasyonu; başlangıç düzeyinde hileyi azaltıp ilerlemeyi kolaylaştırır."),
    ("Rope Overhead Triceps Extension", "İp Overhead Triceps, Rope Overhead Extension", "Triceps",
     "stretch_isolation", True, False, "cable",
     "Dirsekleri yukarıda tut, ipi başın arkasında kontrollü indir, tam ekstansiyonda sık", "10-15", "shoulder|elbow",
     "long_head", 8.8, "lengthened", "beginner", "push", "isolation",
     "hypertrophy",
     "Kabloyla triceps long head'ı omuz fleksiyonunda uzun pozisyonda yükler; dambıl/bar varyantlarına alternatif sağlar."),
    ("Donkey Calf Raise", "Eşek Baldır, Donkey Calf Raise", "Baldır",
     "stretch_isolation", True, False, "machine",
     "Topukları kontrollü aşağı indir, kısa durakla yukarı çık, dizleri sabit tut", "10-20", "",
     "gastrocnemius", 8.1, "lengthened", "beginner", "push", "isolation",
     "hypertrophy",
     "Diz daha açık pozisyonda gastrocnemius'u tam ROM ile yükler; standing calf raise'a ekipman alternatifi sunar."),
]


def evidence_exercise_count() -> int:
    return len(EVIDENCE_EXERCISES)


def evidence_exercises_by_group() -> dict[str, list[tuple]]:
    groups: dict[str, list[tuple]] = {}
    for rec in EVIDENCE_EXERCISES:
        groups.setdefault(rec[2], []).append(rec)
    return groups
