"""
Bilgi katmanı başlangıç verisi (idempotent seed).

- FOOD_SEED: USDA SR Legacy ortak besinleri + TÜRK MUTFAĞI ELLE KÜRASYONU.
  USDA Türk yemeklerini (menemen, mercimek çorbası, kuru fasulye...) ya hiç
  içermez ya da zayıf temsil eder - bu boşluk local_tr kaynaklı kayıtlarla kapatılır.
  Makro değerleri 100g başına, bilinen besin kompozisyonu referanslarından (TÜİK,
  USDA, Tofasp) doğrulanmış tipik değerlerdir.
- EXERCISE_SEED: ai_core prompt'una hardcoded olan hipertrofi öncelik listesinin
  tabloya taşınmış hali (kanonik isim + takma adlar + gerekçe + rep bias).
- RESEARCH_SEED: hacim/frekans/gerilme/deload bulgularının küratörlü özeti (PMID'li).
"""

# (name, aliases, category, kcal, P, K, Y, fiber, portion_g, tags)
FOOD_SEED = [
    # --- TÜRK MUTFAĞI (local_tr) ---
    ("Menemen", "menemen yumurtalı", "dish_tr", 110, 6.5, 5.0, 7.0, 1.5, 250, "vegetarian,gluten_free"),
    ("Mercimek Çorbası", "kırmızı mercimek çorbası", "dish_tr", 85, 5.0, 13.0, 1.5, 3.5, 250, "vegan,vegetarian,gluten_free"),
    ("Kuru Fasulye", "kuru fasulye pilavıyla", "dish_tr", 120, 6.0, 18.0, 2.5, 5.5, 250, "vegan,vegetarian,gluten_free"),
    ("Bulgur Pilavı", "bulgur, domatesli bulgur", "grain", 110, 3.5, 22.0, 1.0, 3.0, 150, "vegan,vegetarian"),
    ("Nohut Yahnisi", "nohut", "dish_tr", 125, 6.5, 16.0, 3.5, 5.0, 220, "vegan,vegetarian,gluten_free"),
    ("İzgara Köfte", "ev köftesi", "dish_tr", 215, 20.0, 4.0, 13.0, 0.5, 150, "high_protein,gluten_free"),
    ("Lahmacun", "lahmacun ince hamur", "dish_tr", 250, 11.0, 30.0, 9.0, 1.5, 120, ""),
    ("Izgara Tavuk Şiş", "tavuk şiş, şiş tavuk", "protein_source", 165, 31.0, 0.0, 3.5, 0.0, 150, "high_protein,gluten_free,lactose_free"),
    ("Ayran", "sulu yoğurt", "dairy", 38, 1.9, 2.8, 1.8, 0.0, 200, "vegetarian,gluten_free"),
    ("Tarhana Çorbası", "tarhana", "dish_tr", 70, 2.5, 10.0, 2.0, 1.0, 250, "vegetarian"),
    ("Simit", "susamlı simit", "grain", 300, 9.0, 52.0, 6.0, 2.5, 100, "vegetarian"),
    ("Börek (peynirli)", "peynirli börek, su böreği", "dish_tr", 290, 9.0, 28.0, 15.0, 1.5, 120, "vegetarian"),
    ("Pilav (beyaz)", "beyaz pilav, pirinç pilavı", "grain", 135, 2.8, 26.0, 2.3, 0.5, 150, "vegan,vegetarian"),
    ("Şakşuka", "patlıcanlı şakşuka", "dish_tr", 95, 2.0, 8.0, 6.0, 3.0, 200, "vegan,vegetarian,gluten_free"),
    ("Izgara Balık (levrek)", "levrek, ızgara balık", "protein_source", 135, 24.0, 0.0, 4.0, 0.0, 180, "high_protein,gluten_free,lactose_free"),
    ("Hamsi Tava", "hamsi", "protein_source", 230, 18.0, 10.0, 13.0, 0.0, 150, "high_protein"),
    ("Süzme Peynir", "labne süzme, lor", "dairy", 105, 16.0, 3.0, 3.0, 0.0, 60, "vegetarian,gluten_free,high_protein"),
    ("Kebap (adana)", "adana kebap, urfa kebap", "dish_tr", 240, 22.0, 3.0, 15.0, 0.3, 160, "high_protein,gluten_free"),
    ("Zeytinyağlı Taze Fasulye", "taze fasulye", "vegetable", 80, 2.0, 8.0, 4.5, 3.5, 200, "vegan,vegetarian,gluten_free"),
    ("Tahinli Pekmez", "tahin pekmez karışımı", "fat", 320, 6.0, 32.0, 19.0, 2.0, 30, "vegan,vegetarian"),
]

# USDA ortak besinleri (usda kaynaklı, SR Legacy tipik değerleri)
FOOD_SEED_USDA = [
    ("Tavuk Göğsü (ızgara)", "tavuk gögsu, chicken breast", "protein_source", 165, 31.0, 0.0, 3.6, 0.0, 150, "high_protein,gluten_free,lactose_free"),
    ("Yumurta (haşlanmış)", "yumurta, egg", "protein_source", 155, 13.0, 1.1, 11.0, 0.0, 60, "vegetarian,gluten_free,high_protein"),
    ("Sığır Eti (kırmızı, yağsız)", "kırmızı et, dana eti", "protein_source", 217, 26.0, 0.0, 12.0, 0.0, 150, "high_protein,gluten_free,lactose_free"),
    ("Hindi Göğsü", "hindi eti", "protein_source", 135, 29.0, 0.0, 1.5, 0.0, 150, "high_protein,gluten_free,lactose_free"),
    ("Somon (ızgara)", "salamon", "protein_source", 208, 20.0, 0.0, 13.0, 0.0, 150, "high_protein,gluten_free"),
    ("Yulaf", "yulaf ezmesi, oat", "grain", 389, 16.9, 66.0, 6.9, 10.6, 60, "vegan,vegetarian"),
    ("Tam Buğday Ekmeği", "tam tahıl ekmek", "grain", 247, 13.0, 41.0, 3.4, 7.0, 40, "vegetarian"),
    ("Pirinç (haşlanmış)", "haşlanmış pirinç", "grain", 130, 2.7, 28.0, 0.3, 0.4, 150, "vegan,vegetarian,gluten_free"),
    ("Patates (haşlanmış)", "patates", "vegetable", 87, 2.0, 20.0, 0.1, 1.8, 200, "vegan,vegetarian,gluten_free"),
    ("Tatlı Patates", "şeker patatesi", "vegetable", 86, 1.6, 20.0, 0.1, 3.0, 180, "vegan,vegetarian,gluten_free"),
    ("Brokoli", "brokoli", "vegetable", 34, 2.8, 7.0, 0.4, 2.6, 200, "vegan,vegetarian,gluten_free"),
    ("Yoğurt (sade)", "yoğurt, plain yogurt", "dairy", 61, 3.5, 4.7, 3.3, 0.0, 200, "vegetarian,gluten_free"),
    ("Süt (yarım yağlı)", "süt, milk", "dairy", 50, 3.4, 4.8, 1.9, 0.0, 200, "vegetarian,gluten_free"),
    ("Beyaz Peynir", "beyaz peynir", "dairy", 264, 17.0, 2.0, 21.0, 0.0, 60, "vegetarian,gluten_free,low_carb"),
    ("Badem", "badem", "fat", 579, 21.0, 22.0, 50.0, 12.5, 30, "vegan,vegetarian"),
    ("Ceviz", "ceviz", "fat", 654, 15.0, 14.0, 65.0, 6.7, 30, "vegan,vegetarian"),
    ("Muz", "muz", "fruit", 89, 1.1, 23.0, 0.3, 2.6, 120, "vegan,vegetarian,gluten_free"),
    ("Elma", "elma", "fruit", 52, 0.3, 14.0, 0.2, 2.4, 180, "vegan,vegetarian,gluten_free"),
    ("Mercimek (pişmiş)", "yeşil mercimek", "protein_source", 116, 9.0, 20.0, 0.4, 8.0, 200, "vegan,vegetarian,gluten_free"),
    ("Zeytinyağı", "zeytin yağı", "fat", 884, 0.0, 0.0, 100.0, 0.0, 15, "vegan,vegetarian,gluten_free,low_carb"),
    ("Whey Protein", "protein tozu", "supplement", 380, 78.0, 8.0, 4.0, 1.0, 30, "vegetarian,gluten_free,high_protein,lactose_free"),
    ("Lor Peyniri", "lor", "dairy", 98, 11.0, 3.5, 4.0, 0.0, 100, "vegetarian,gluten_free,high_protein"),
]

# (name, aliases, muscle_group, exercise_type, stretch, unilateral, equipment, cue, rep_bias, contra, evidence, reason)
EXERCISE_SEED = [
    # --- GÖĞÜS ---
    ("Incline Dumbbell Press", "Eğimli Dambbell Press, Incline DB Press", "Göğüs", "primary_compound", False, False, "dumbbell",
     "Gözü seviyesinde eğim (30-45°), dambbelli alt göğüs hattında indir", "6-10", "", None,
     "Eğimli varyant üst göğsü tam gerilimde yükler; flat'e göre ön deltoid yükü azdır"),
    ("Incline Barbell Bench Press", "Eğimli Barbell Bench", "Göğüs", "primary_compound", False, False, "barbell",
     "30° eğim, çubuk klavikül hattına insin", "6-10", "", None,
     "Üst göğüs fiberlerine en iyi mekanik gerilimi veren barbell bileşiği"),
    ("Flat Barbell Bench Press", "Bench Press, Göğüs Bench", "Göğüs", "primary_compound", False, False, "barbell",
     "Kürek kemiklerini sıkıştır, dirsekler 45-75°", "5-8", "", "",
     "En ağır yüklenebilir göğüs bileşiği; günde en fazla 1 ana bileşik olarak yer almalı"),
    ("Incline Dumbbell Fly-Press Hybrid", "Fly Press Hibrit, DB Fly Press", "Göğüs", "stretch_isolation", True, False, "dumbbell",
     "Ellerin inerken kürek kemikleri yastığa yaslanır, gerilme hisset", "10-12", "", "",
     "Göğsü tam gerilmiş pozisyonda yükler; mekanik gerilimi uzun hareket aralığında verir"),
    ("Cable Crossover", "Kablolu Çapraz, Cable Fly", "Göğüs", "stretch_isolation", True, False, "cable",
     "Kollar yukarıdan aşağıya, göğsü sıkıştırırken 1 sn tut", "12-15", "", "",
     "Yükü tüm hareket aralığında koruyan tam-germe izolasyonu"),
    ("Weighted Dip", "Ağırlıklı Dip, Dip", "Göğüs", "secondary_compound", True, False, "bodyweight",
     "Gövde hafif öne eğik, dirsekler dışa açık", "8-12", "shoulder", "",
     "Göğsü gerilmiş pozisyonda yükleyen bileşik; omuz sakatlığında dikkat"),
    # --- SIRT ---
    ("Weighted Pull-up", "Ağırlıklı Barfiks, Pull-up", "Sırt", "primary_compound", True, False, "bodyweight",
     "Kürek kemiklerini aşağı çek, göğüs bar'a yaklaş", "6-10", "", None,
     "Sırtın en yüksekte gerildiği bileşik; lat fiberlerine tam gerilimde yük"),
    ("Lat Pull-down", "Kablolu Öne Çekiş, Pull-down", "Sırt", "secondary_compound", True, False, "cable",
     "Göğsü bar'a yaklaştır, kollarla değil kürekle çek", "8-12", "", "",
     "Pull-up varyasyonu; yükü tüm gerilim aralığında koruyan kablo yolu"),
    ("Barbell Row", "Barbell Çekiş, Kürek Çekiş", "Sırt", "primary_compound", False, False, "barbell",
     "Torso 45° öne eğik, kalça geriye, çubuğu karna çek", "8-10", "lower_back", "",
     "Orta sırt ve lat'a ağır yüklenen bileşik; bel sakatlığında göğüs destekli row'a çevir"),
    ("Chest-Supported Row", "Göğüs Destekli Row, Incline DB Row", "Sırt", "secondary_compound", False, False, "machine",
     "Göğüs pedala yapışık, kürek kemiklerini sıkıştır", "10-12", "", "",
     "Bel yükü sıfır; sakatlık güvenli sırt hacmi kaynağı"),
    ("Dumbbell Pull-over", "Lat Prayer, Pull-over", "Sırt", "stretch_isolation", True, False, "dumbbell",
     "Dambbelli başın arkasına derin indir, kaburgayı aç", "10-15", "", "",
     "Lat'ı uzun fiber hattında geren tam-germe izolasyonu"),
    # --- BACAK: QUADRICEPS ---
    ("Front Squat", "Öne Squat, Front Squat", "Quadriceps", "primary_compound", False, False, "barbell",
     "Dirsekler yukarı, ATG derinlik, kalça dizle yukarı", "6-10", "knee", None,
     "ATG derinlikte quad fiberlerine maksimum gerilme"),
    ("ATG Split Squat", "Derin Split Squat, Bulgarian Split Squat", "Quadriceps", "unilateral", True, True, "dumbbell",
     "Arka ayak yüksek, ön diz üstüne insin, ön bacak dikey", "8-12", "knee", "",
     "Tam derinlikte tek-taraf yük; asimetri düzeltir, quad gerilimini artırır"),
    ("Leg Press", "Bacak Press, Derin Leg Press", "Quadriceps", "secondary_compound", True, False, "machine",
     "Derinlik öncelikli: dizleri göğse yaklaştır", "10-15", "knee", "",
     "Bileşiği yüksek hacimle yükleme kaynağı; derin pozisyonda quad gerilimi"),
    ("Hack Squat", "Hack Squat Makinesi", "Quadriceps", "secondary_compound", False, False, "machine",
     "Kalça sabit, derin inip kontrollü çık", "8-12", "knee", "",
     "Kaburgadan bağımsız ağır quad hacmi; stabil iz yol"),
    ("Leg Extension", "Bacak Üstü, Quad Extension", "Quadriceps", "shortened_isolation", False, False, "machine",
     "Uzama pozisyonunda 1 sn sıkıştır", "12-20", "knee", "",
     "Kısalan pozisyonda quad izolasyonu; üçlü kurulumun son halkası"),
    # --- BACAK: HAMSTRING & GLUTE ---
    ("Romanian Deadlift", "RDL, Deadlift Rumen", "Hamstring & Glute", "primary_compound", True, False, "barbell",
     "Dizler hafif bükülü, kalça geriye, hamstring gerilimini hisset", "6-10", "lower_back", None,
     "Hamstring'i uzun pozisyonda yükleyen ana bileşik"),
    ("Hip Thrust", "Kalça İtiş, Kalça Yükseltme", "Hamstring & Glute", "primary_compound", False, False, "barbell",
     "Kalçayı kilitli, glute'u sıkıştır, 1 sn tut", "8-12", "", "",
     "Glute'un en yüksek güç üretimi pozisyonda yüklendiği bileşik"),
    ("Seated Leg Curl", "Oturarak Bacak Arkası", "Hamstring & Glute", "shortened_isolation", False, False, "machine",
     "Kalça yastığa yapışık, kontrollü dön", "10-15", "", "",
     "Kalça bükülü pozisyonda hamstring izolasyonu (uzun+kısa baş hedefi)"),
    ("Good Morning", "Good Morning", "Hamstring & Glute", "secondary_compound", True, False, "barbell",
     "Dizler sabit, kalça geriye, çubuk omuzda", "8-12", "lower_back", "",
     "Hamstring'i gerilmiş pozisyonda yükleyen varyant; bel sakatlığında RDL'ye çevir"),
    # --- OMUZ ---
    ("Lean-away Cable Lateral Raise", "Yana Yatış Kablolu Yan Omuz", "Omuz", "stretch_isolation", True, False, "cable",
     "Kürek kemiklerini sabit, yükte gerilmeye bırak", "12-15", "", "",
     "Yan deltoid'e gerilmiş pozisyonda yük (dumbbell'a göre uzun TUT süresi)"),
    ("Dumbbell Lateral Raise", "Yan Omuz Yükseltme, Lateral Raise", "Omuz", "shortened_isolation", False, False, "dumbbell",
     "Omuzları kulaktan uzak, dirsekler el hizasında", "12-20", "", "",
     "Yan deltoid kısa-pozisyon izolasyonu"),
    ("Reverse Pec-Deck", "Ters Makine Kuşu, Reverse Fly", "Omuz", "shortened_isolation", False, False, "machine",
     "Omuzlar aşağı, kürek sıkıştırmadan arka deltoidi izole et", "12-15", "", "",
     "Arka deltoid için en stabil izolasyon (postural denge)"),
    ("Cable Face Pull", "Yüze Çekiş, Face Pull", "Omuz", "secondary_compound", False, False, "cable",
     "Yükü alnına doğru çek, dışa rotasyon", "12-15", "", "",
     "Arka deltoid + rotator cuff sağlığı (prehab kaynak)"),
    ("Overhead Press", "Baş Üstü Press, OHP", "Omuz", "primary_compound", False, False, "barbell",
     "Kalça kilitli, çubuğu kulak hizasından geçir", "6-10", "shoulder", "",
     "Ön deltoid ağır yüklü bileşik; omuz sakatlığında DB varyanta çevir"),
    # --- KOL ---
    ("Incline Dumbbell Curl", "Eğimli Dambbell Biceps", "Biceps", "stretch_isolation", True, False, "dumbbell",
     "Gövde yastığa yaslı, kol geride, tam gerilme", "10-12", "", "",
     "Biceps'i gerilmiş pozisyonda yükleyen en iyi varyant"),
    ("Bayesian Cable Curl", "Kablolu Gerilmiş Curl", "Biceps", "stretch_isolation", True, False, "cable",
     "Yükün çekilmesiyle kolu geriye gerdir", "12-15", "", "",
     "Kablo yoluyla tüm hareket aralığında gerilimi koruyan curl"),
    ("Preacher Curl", "Scott Curl, Preacher", "Biceps", "shortened_isolation", False, False, "dumbbell",
     "Kol yastıkta, peak kasılmada sıkıştır", "10-15", "", "",
     "Kısalan pozisyonda biceps izolasyonu"),
    ("Overhead Cable Triceps Extension", "Baş Üstü Kablolu Triceps", "Triceps", "stretch_isolation", True, False, "cable",
     "Dirsek sabit, uzun pozisyona derin indir", "10-15", "", None,
     "Triceps uzun başını gerilmiş pozisyonda yükleyen varyant"),
    ("Close-grip Press", "Dar Tutuş Bench, Close-grip Bench", "Triceps", "secondary_compound", False, False, "barbell",
     "Dirsekler gövdeye yakın, kürek sabit", "8-12", "", "",
     "Triceps ağır yüklü bileşik (uzun baş kısalan pozisyonda)"),
    ("Cross-body Triceps Extension", "Çapraz Triceps", "Triceps", "shortened_isolation", False, False, "cable",
     "Kolu gövde çaprazında uzat, peak'te sıkıştır", "12-15", "", "",
     "Lateral head short-pozisyon izolasyonu"),
    # --- KARIN / CORE ---
    ("Ab-wheel Rollout", "Ab-wheel, Karın Tekerleği", "Karın", "primary_compound", True, False, "bodyweight",
     "Pelvis sabit, kaburgayı açıp gerilmeye bırak", "8-12", "lower_back", "",
     "Karın gerilmiş pozisyonda yük; bel sakatlığına alternatif Cable Crunch"),
    ("Hanging Leg Raise", "Asılı Bacak Kaldırma", "Karın", "primary_compound", True, False, "bodyweight",
     "Kontrollü kaldır, sallanma yok", "10-15", "", "",
     "Hip flexor'la karın ayrımı; derin gerilme kontrolü"),
    ("Cable Crunch", "Kablolu Karın", "Karın", "shortened_isolation", False, False, "cable",
     "Pelvis sabit, kaburgayı aşağı kıvır", "12-15", "", "",
     "Ağırlıklı kısalan-pozisyon karın izolasyonu"),
    ("Weighted Plank", "Ağırlıklı Plank", "Karın", "core_prehab", False, False, "bodyweight",
     "Kalçadan kavis alma, kürek sıkıştır", "12-20", "", "",
     "Statik core sağlığı; prehab kaynak"),
]

# (topic, title, summary, finding_rule, evidence_refs, target_muscle_group, relevance_score)
RESEARCH_SEED = [
    ("volume", "Haftalık set sayısı hipertrofi doz-yanıt ilişkisi",
     "Haftalık set sayısı ile hipertrofi arasında doz-yanıt ilişkisi görülür; ancak bireysel yanıt değişir ve tek bir evrensel optimum aralık kanıtlanmış değildir.",
     "Hacmi kademeli artır; toparlanma, performans ve ilerleme verisine göre kişiselleştir.", "PMID:27433992", None, 10),
    ("volume", "MEV/MAV/MRV hacim landmarkları",
     "MEV/MAV/MRV pratik karar çerçeveleridir; araştırma tek bir evrensel landmark tablosunu doğrulamaz. Hacim yanıtı bireysel ve ilerleme/toparlanma verisiyle ayarlanmalıdır.",
     "Landmarkları başlangıç hipotezi olarak kullan; performans düşüşü, ağrı ve toparlanma verisiyle hacmi azalt veya artır.", "PMID:35873210", None, 9),
    ("frequency", "Kas grubu başına haftalık frekans",
     "Toplam hacim eşitlendiğinde frekansın hipertrofi üzerindeki bağımsız etkisi sınırlı görünür; frekansı artırmak hacmi kaliteli oturumlara bölmek için yararlıdır.",
     "Çoğu kası 2 veya daha fazla oturuma bölmeyi tercih et; bunu katı bir üstünlük kuralı yapma.", "PMID:30558493", None, 10),
    ("frequency", "Oturum başına hacim verimliliği",
     "Oturum başına kas grubu hacmi ~8 seti geçince kalite düşer; hacmi oturumlara dağıtmak frekans üstünlüğünün temelidir.",
     "Oturum başına aynı kas grubuna 8 setin üzerine taşma; hacmi ikinci oturuma dağıt.", "PMID:30558493", None, 8),
    ("stretch", "Gerilmiş pozisyonda yük (lengthened loading)",
     "Uzun kas boyunda direnç antrenmanı bazı sonuçlarda avantajlı görünebilir; güncel derlemeler kanıtın kas ve ölçüm yöntemine göre karışık olduğunu bildirir.",
     "Uygunsa uzun kas boyunda yüklenen hareketleri kullan; bunu güvenlik ve tam hareket açıklığıyla birlikte değerlendir.", "PMID:36662126", None, 10),
    ("stretch", "Uzun-kas pozisyonu mekanik gerilim",
     "Uzun kas pozisyonu bazı kaslarda daha fazla bölgesel büyümeyle ilişkili olabilir; etki evrensel değildir ve kesin sıralama çıkarılamaz.",
     "İzolasyonda uzun pozisyon varyantlarını kanıt düzeyi ve kullanıcının toleransına göre dönüşümlü değerlendir.", "PMID:41646176", None, 9),
    ("periodization", "Planlı periodizasyon vs doğrusal artış",
     "Yeterli hacim/intensite korunduğunda periodizasyon şeması hipertrofi sonucunu az belirgin değiştirir; süreklilik daha önemli.",
     "Şema karmaşasından kaçın: kullanıcıya uygun, sürdürülebilir bir ilerleme modeli seç ve performans verisiyle güncelle.", "PMID:35044672", None, 7),
    ("deload", "Deload toparlanma etkisi",
     "Bir haftalık deload, incelenen kısa çalışmada hipertrofiyi artırmadı; bazı kuvvet sonuçları kesintisiz antrenman lehineydi. Deload kişisel yorgunluk ve performans göstergelerine göre uygulanmalıdır.",
     "Deloadı takvim zorunluluğu değil; birikmiş yorgunluk, performans düşüşü veya ağrı sinyali olduğunda kullanılan araç olarak değerlendir.", "PMID:38274324", None, 8),
    ("recovery", "Uyku ve hipertrofi",
     "Yetersiz uyku (<7 saat) hipertrofi ve yağ-kas oranını negatif etkiler; antrenman hacmini uyku kalitesine göre ayarla.",
     "Uyku kalitesi düşükse toparlanma ve performans geri bildirimini izle; gerektiğinde o günkü yoğunluk/hacmi muhafazakâr ayarla.", "PMID:28919335", None, 7),
    ("protein", "Protein alımı dozu ve dağılımı",
     "Günlük 1.6-2.2 g/kg protein hipertrofi için optimum; oturum başına 25-45g doz ve güne dağıtım uyumu önemli.",
     "Günlük protein hedefini kişinin kilosu, hedefi ve klinik durumuna göre belirle; yeterli toplam alımı gün içine dağıt.", "PMID:28698222,PMID:36057893", None, 10),
    ("recovery", "Sakatlık öncesi prehab hacmi",
     "Omuz sakatlığı önleme programları için bazı olumlu bulgular olsa da kanıt sınırlı ve popülasyona özgüdür; genel prehab hacmi için kesin doz çıkarılamaz.",
     "Prehabı tanı/tedavi yerine koyma; risk, spor dalı ve semptomlara göre düşük maliyetli destek olarak değerlendir.", "PMID:34560586", None, 6),
    ("protein", "Kalori fazlası ve kas kazanımı",
     "Enerji fazlasının hipertrofi için gerekli büyüklüğü belirsizdir; daha büyük fazlalar incelenen çalışmada başlıca yağ artışıyla ilişkiliydi.",
     "Bulkta küçük ve izlenen bir enerji fazlası kullan; vücut ağırlığı/yağ artışı hızlanırsa kaloriyi azalt.", "PMID:31482093,PMID:37914977", None, 8),
]
